### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by Chapi15** [Chapi15/chapi15.github.io#2]
The main page is different, perhaps it is related to the missing **index.html** file
# Tasks
- [x] Get the **index.html** out of the EN folder
- [x] Get the **index.html (ES)** out of the ES folder

**Comment by Chapi15** [comment]
- [x] Fix the broken link for the **Home** option in the navigation menu
   - Applies for the EN and ES
